# cd.yml
name: CD

on:
  push:
    branches:
      - deploytests

jobs:
  # CD
  deploy_android:
    runs-on: ubuntu-latest
    # Beta release only
    if: github.ref == 'refs/heads/deploytests'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Github commit count
        run: git rev-list HEAD --count
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
            java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
            flutter-version: '1.22.x'

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Cache bundle dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Build Android App Bundle
        run: flutter build appbundle --flavor prod --build-number=$(git rev-list HEAD --count)
      - name: Build Android apks
        run: flutter build apk --split-per-abi --flavor prod --build-number=$(git rev-list HEAD --count)          
      - name: Download bundle dependencies
        run: |
          gem install bundler:2.6.6
          bundle config path vendor/bundle
          bundle install   
        working-directory: android/fastlane
      - script@1:
       title: Execute fastlane override values.
       run_if: '{{getenv "FASTLANE_OVERRIDE_EXECUTED" | eq "" }}'
       inputs:
       - content: |
           #!/usr/bin/env bash
           set -e
           echo "[INFO] Setting the faslane version to 2.152.0  "
           gem install fastlane --version 2.152.0 --no-document
           #set the flag so this step will no longer execute if called again in
           # the same execution
           envman add --key "FASTLANE_OVERRIDE_EXECUTED" --value "true"
      - name: Release to Google Play (beta)
        run: |
          bundle exec fastlane beta 
        working-directory: android/fastlane
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN}}
